### ISSUE TITLE
Update XML File to contain the newly released episodes

### ISSUE THREAD

**Issue by techaddicted** [tsujamin/evan-doorbell-podcast#1]
The production tapes [1] contain new episodes, could you therefore update the XML so that they show up in the Podcast feed?

[1] https://evan-doorbell.com/production-tapes/

**Comment by tsujamin** [comment]
Hey mate

Happy to take a PR to manually add those new episodes (the feed is Group 1 not Production tapes though), but the site has changed significantly since I scraped together the Podcast feed so its not straight forward to regenerate it.

I'll have a look over the weekend if I get a chance to see if I can do a new feed from the updated site

**Comment by techaddicted** [comment]
Perfect, thank you so much!

**Comment by tsujamin** [comment]
No worries, but no promises 🤞

**Comment by tsujamin** [comment]
Not my finest work (it's not straight forward to pick a good order for the production tapes as they have minimal metadata) but check out the new group 1 and production tapes playlist in the readme. The latter I'll try keep up to date as new tapes are released.

**Comment by techaddicted** [comment]
Amazing, thank you so much.
